//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppWCF_Interface2037
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntiteReponse
    {
        public int Id { get; set; }
        public string Contenu { get; set; }
        public int question_fid { get; set; }
    
        public virtual EntiteQuestion questions { get; set; }
    }
}
