//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppWCF_Interface2037
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntiteQuestion
    {
        public int id { get; set; }
        public string question { get; set; }
    }
}
