//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppWCF_Interface2037
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class web_serviceEntities : DbContext
    {
        public web_serviceEntities()
            : base("name=web_serviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EntiteQuestion> questions { get; set; }
        public DbSet<EntiteReponse> reponses { get; set; }
    
        public virtual int AjouterQuestion(string p_question)
        {
            var p_questionParameter = p_question != null ?
                new ObjectParameter("p_question", p_question) :
                new ObjectParameter("p_question", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AjouterQuestion", p_questionParameter);
        }
    
        public virtual int AjouterReponse(string p_reponse, Nullable<int> p_fid_question)
        {
            var p_reponseParameter = p_reponse != null ?
                new ObjectParameter("p_reponse", p_reponse) :
                new ObjectParameter("p_reponse", typeof(string));
    
            var p_fid_questionParameter = p_fid_question.HasValue ?
                new ObjectParameter("p_fid_question", p_fid_question) :
                new ObjectParameter("p_fid_question", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AjouterReponse", p_reponseParameter, p_fid_questionParameter);
        }
    }
}
